import React from "react";
import Head from "next/head";
import Main from "./main";
import AboutMe from "./aboutMe";
import Works from "./works";
import { ContactMe } from "../components";

const Home = () => {
  return (
    <>
      <Head>
        <title>FE 박영은</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-4">
        <Main />
        <AboutMe />
        <Works />
        <ContactMe />
      </div>
    </>
  );
};
export default Home;
